defaults:
  - model_settings: deepseek_coder_1b_instruct_16384 # Name of model settings file
  - inference_settings: 1024_1.yaml # Name of training data settings file
  - prompt_config: cot_prompt_config # Name of training settings file
  - override hydra/job_logging: 'disabled'

solver_type: CodeSolver
solver_args:
prompt_config:
  prompt_type: CodePrompt
inference_settings:
  stop_tokens:
    - '[END CODE]'