defaults:
  - model_settings: deepseek_math_7b_rl_4096 # Name of model settings file
  - inference_settings: 1024_1.yaml # Name of training data settings file
  - prompter_config: cot_prompter_config # Name of training settings file
  - override hydra/job_logging: 'disabled'
  - _self_

solver_or_tool_type: ExecutionTool
solver_or_tool_args:
  timeout_in_secs: 15.0