defaults:
  - model_settings: gpt-4o-mini # Name of model settings file
  - inference_settings: 1024_1.yaml # Name of training data settings file
  - prompt_config: cot_prompt_config # Name of training settings file
  - override hydra/job_logging: 'disabled'

solver_or_tool_type: OldPlannerTool
solver_or_tool_args:
prompt_config:
  prompt_type: OldPlannerPrompt
inference_settings:
  stop:
    - '[END PROCEDURE]'