defaults:
  - model_settings: gpt-4o-mini # Name of model settings file
  - inference_settings: 1024_1.yaml # Name of training data settings file
  - prompter_config: cot_prompter_config # Name of training settings file
  - override hydra/job_logging: 'disabled'
  - _self_

solver_or_tool_type: PlannerTool
solver_or_tool_args:
prompter_config:
  prompter_type: PlannerPrompter
  system_prompt_path: prompts/planner_system_prompt.txt
# inference_settings:
#   stop:
#     - '[END PROCEDURE]'