defaults:
  - model_settings: codet5_small_2048 # Name of model settings file
  - inference_settings: 1024_1.yaml # Name of training data settings file
  - prompter_config: test_prompter_config # Name of training settings file
  - override hydra/job_logging: 'disabled'
  - _self_

solver_or_tool_type: TestSolver
solver_or_tool_args: