defaults:
  - model_settings: deepseek_math_7b_rl_4096 # Name of model settings file
  - inference_settings: 1024_1.yaml # Name of training data settings file
  - prompt_config: cot_prompt_config # Name of training settings file
  - override hydra/job_logging: 'disabled'

solver_or_tool_type: VanillaFewShotSolver
solver_or_tool_args: