# @package _global_
defaults:
  - override hydra/job_logging: 'disabled'

task_type: IMPL_CORRECTNESS
log_dir: ".logs/eval_few_shot_impl_plan_few_shot_proof"
exp_name: "few_shot_impl_plan_few_shot_proof"
impl_generation_strategy: "PlanningCopraImplGenerator"
# problems_to_solve: "*"
problems_to_solve: [2, 8, 17, 23, 26, 30, 41, 45, 65]
k: 1
# timeout_in_ses: 3600
timeout_in_ses: 600
params:
  proof_dump_file_path: "proofs.txt"
  num_implementation_samples: 5
  num_proof_plan_samples: 5
  uses_copra_prover: true
  impl_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotImplGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotImplGeneration.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  impl_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  prover_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotImplProofGenerationBasedOnPlan.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotImplProofGenerationBasedOnPlan.md"
    max_tokens_per_action: 400
    max_history_messages: 0
    end_tokens: ["[END]"]
  prover_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.9
  proof_planner_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ProofPlanner.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ProofPlanner.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  proof_planner_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.9
  impl_planner_model_settings: null
  impl_planner_prompt_settings: null
  # impl_planner_prompt_settings:
  #   system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ImplementationPlanner.md"
  #   example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplementationPlanner.md"
  #   max_tokens_per_action: 10000
  #   max_history_messages: 0
  #   end_tokens: ["[END]"]
  # impl_planner_model_settings:
  #   model_name: "gpt-4o"
  #   secret_path: ".secrets/openai_key.json"
  #   temperature: 0.75