# @package _global_
defaults:
  - override hydra/job_logging: 'disabled'

task_type: IMPL_CORRECTNESS
log_dir: ".logs/eval_few_shot_impl_proof_plan_copra_proof"
exp_name: "few_shot_impl_proof_plan_copra_proof"
impl_generation_strategy: "ImplGenerator"
# problems_to_solve: [0, 3, 4, 8, 9, 52, 55, 57, 72, 73, 88, 92, 95, 100, 102, 106, 121, 126, 136, 138, 139, 150, 151, 152, 155, 159, 163]
# problems_to_solve: [3, 9, 55, 57, 136]
problems_to_solve: "*"
k: 1
timeout_in_ses: 600
params:
  proof_dump_file_path: "proofs.txt"
  num_implementation_samples: 1000
  num_proof_plan_samples: 1000
  uses_copra_prover: true
  impl_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotImplGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotImplGeneration.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  impl_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  prover_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/Copra.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplCopra.md"
    max_tokens_per_action: 400
    max_history_messages: 0
    end_tokens: ["[END]"]
  prover_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.9
  proof_planner_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ImplProofPlanner.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplProofPlanner.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  proof_planner_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.9
  impl_planner_model_settings: null
  impl_planner_prompt_settings: null
  # impl_planner_prompt_settings:
  #   system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ImplementationPlanner.md"
  #   example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplementationPlanner.md"
  #   max_tokens_per_action: 10000
  #   max_history_messages: 0
  #   end_tokens: ["[END]"]
  # impl_planner_model_settings:
  #   model_name: "gpt-4o"
  #   secret_path: ".secrets/openai_key.json"
  #   temperature: 0.75