# @package _global_
defaults:
  - override hydra/job_logging: 'disabled'

task_type: IMPL_CORRECTNESS
log_dir: ".logs/eval_few_shot_impl_proof_plan_copra_proof_o4_mini"
exp_name: "few_shot_impl_proof_plan_copra_proof_o4_mini"
impl_generation_strategy: "ImplGenerator"
problems_to_solve: "*"
# problems_to_solve: [2, 3, 8, 9, 17, 41, 45, 53, 57, 72, 85, 144, 159]
k: 1
timeout_in_secs: 1000
params:
  proof_dump_file_path: "proofs.txt"
  num_implementation_samples: 1000
  num_proof_plan_samples: 1000
  uses_copra_prover: true
  impl_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotImplGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotImplGeneration.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  impl_model_settings:
    model_name: "o4-mini"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  prover_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/Copra.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplCopra.md"
    max_tokens_per_action: 400
    max_history_messages: 0
    end_tokens: ["[END]"]
  prover_model_settings:
    model_name: "o4-mini"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  proof_planner_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ImplProofPlanner.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplProofPlanner.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  proof_planner_model_settings:
    model_name: "o4-mini"
    secret_path: ".secrets/openai_key.json"
    reasoning_effort: low
    reasoning_token_count: 7500
    temperature: 0.75
  impl_planner_model_settings: null
  impl_planner_prompt_settings: null
  # impl_planner_prompt_settings:
  #   system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ImplementationPlanner.md"
  #   example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplementationPlanner.md"
  #   max_tokens_per_action: 10000
  #   max_history_messages: 0
  #   end_tokens: ["[END]"]
  # impl_planner_model_settings:
  #   model_name: "gpt-4o"
  #   secret_path: ".secrets/openai_key.json"
  #   temperature: 0.75