# @package _global_
defaults:
  - override hydra/job_logging: 'disabled'

task_type: SPEC_ISOMORPHISM
log_dir: ".logs/eval_few_shot_spec_few_shot_proof_claude_3_7"
exp_name: "few_shot_spec_few_shot_proof_claude_3_7"
spec_generation_strategy: "IsoGenerator"
problems_to_solve: "*"
k: 1
timeout_in_ses: 600
params:
  proof_dump_file_path: "proofs.txt"
  num_spec_samples: 1000
  num_proof_plan_samples: 1000
  uses_copra_prover: false
  spec_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotSpecGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotSpecGeneration.md"
    max_tokens_per_action: 5000
    max_history_messages: 0
    end_tokens: ["[END]"]
  spec_model_settings:
    model_name: "anthropic.claude-3-7-sonnet-20250219-v1:0"
    secret_path: ".secrets/bedrock_key.json"
    temperature: 0.75
  prover_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotSpecProofGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotSpecProofGeneration.md"
    max_tokens_per_action: 7500
    max_history_messages: 0
    end_tokens: ["[END]"]
  prover_model_settings:
    model_name: "anthropic.claude-3-7-sonnet-20250219-v1:0"
    secret_path: ".secrets/bedrock_key.json"
    temperature: 0.75
  proof_planner_prompt_settings: null
  proof_planner_model_settings: null
  spec_planner_prompt_settings: null
  spec_planner_model_settings: null
  # spec_planner_prompt_settings:
  #   system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ImplementationPlanner.md"
  #   example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplementationPlanner.md"
  #   max_tokens_per_action: 10000
  #   max_history_messages: 0
  #   end_tokens: ["[END]"]
  # spec_planner_model_settings:
  #   model_name: "gpt-4o"
  #   secret_path: ".secrets/openai_key.json"
  #   temperature: 0.75