# @package _global_
defaults:
  - override hydra/job_logging: 'disabled'

task_type: SPEC_ISOMORPHISM
log_dir: ".logs/eval_few_shot_spec_proof_plan_copra_proof"
exp_name: "few_shot_spec_proof_plan_copra_proof"
spec_generation_strategy: "IsoGenerator"
# problems_to_solve: "*"
# problems_to_solve: [2, 8, 17, 23, 26, 30, 41, 45, 65]
problems_to_solve: [45]
k: 1
timeout_in_ses: 1000
params:
  proof_dump_file_path: "proofs.txt"
  num_spec_samples: 5
  num_proof_plan_samples: 5
  uses_copra_prover: true
  spec_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotSpecGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotSpecGeneration.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  spec_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  prover_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/Copra.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/SpecCopra.md"
    max_tokens_per_action: 400
    max_history_messages: 0
    end_tokens: ["[END]"]
  prover_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.9
  proof_planner_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/SpecProofPlanner.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/SpecProofPlanner.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  proof_planner_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.9
  spec_planner_prompt_settings: null
  spec_planner_model_settings: null
  # spec_planner_prompt_settings:
  #   system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ImplementationPlanner.md"
  #   example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplementationPlanner.md"
  #   max_tokens_per_action: 10000
  #   max_history_messages: 0
  #   end_tokens: ["[END]"]
  # spec_planner_model_settings:
  #   model_name: "gpt-4o"
  #   secret_path: ".secrets/openai_key.json"
  #   temperature: 0.75