# @package _global_
defaults:
  - override hydra/job_logging: 'disabled'

task_type: IMPL_CORRECTNESS
log_dir: ".logs/eval_planning_copra_impl_generator"
exp_name: "planning_copra_impl_generator"
impl_generation_strategy: "PlanningCopraImplGenerator"
# problems_to_solve: "*"
problems_to_solve: [2, 8, 13, 23, 27, 31, 42, 45, 48]
k: 1
# timeout_in_ses: 3600
timeout_in_ses: 600
params:
  proof_dump_file_path: "proofs.json"
  num_implementation_plan_samples: 5
  num_proof_plan_samples: 5
  impl_planner_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ImplementationPlanner.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplementationPlanner.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  impl_planner_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  impl_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/Implementer.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/Implementer.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  impl_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  proof_planner_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ProofPlanner.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ProofPlanner.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  proof_planner_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  copra_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/Copra.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/Copra.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  copra_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75