# @package _global_
defaults:
  - override hydra/job_logging: 'disabled'

task_type: IMPL_CORRECTNESS
log_dir: ".logs/eval_planning_copra_impl_generator"
exp_name: "planning_copra_impl_generator"
impl_generation_strategy: "PlanningCopraImplGenerator"
# problems_to_solve: "*"
# problems_to_solve: [2, 8, 17, 23, 26, 30, 41, 45, 65]
problems_to_solve: [45]
k: 1
# timeout_in_ses: 3600
timeout_in_ses: 600
params:
  proof_dump_file_path: "proofs.json"
  num_implementation_samples: 5
  num_proof_plan_samples: 5
  use_impl_planner: false
  use_proof_planner: true
  use_copra: true
  impl_planner_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ImplementationPlanner.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ImplementationPlanner.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  impl_planner_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  impl_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotImplGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotImplGeneration.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  impl_prompt_settings_if_use_impl_planner:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/Implementer.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/Implementer.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  impl_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  proof_planner_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/ProofPlanner.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/ProofPlanner.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  proof_planner_prompt_settings_if_no_proof_planner:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotImplProofThoughtsGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotImplProofThoughtsGeneration.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  proof_planner_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  copra_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/clever_prompts/system/Copra.md"
    example_prompt_path: "src/clever_prover/prompts/clever_prompts/examples/Copra.md"
    max_tokens_per_action: 400
    max_history_messages: 0
    end_tokens: ["[END]"]
  copra_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.9
  few_shot_prover_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotImplSingleProofGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotImplSingleProofGeneration.md"
    max_tokens_per_action: 10000
    max_history_messages: 0
    end_tokens: ["[END]"]
  few_shot_prover_model_settings:
    model_name: "gpt-4o"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75