max_new_tokens: 1024
temperature: 0.9
top_p: 1.0
top_k:
do_sample: true
num_return_sequences: 3
max_length: 2048
return_full_text: false
stop_tokens:
  # - "```output"
  # - "```python"
  # - "```\nOutput"
  # - ")\n```"
  # - "``````output"
  - '[END]'
# ["```output", "```python", "```\nOutput" , ")\n```" , "``````output"]